Repository fandoghpaas/fandogh-cli, pull requests merged in 2018-08, with the labels that each got.

#103 Enhancement/refactor cli commands
  fandogh_cli/base_commands.py
  fandogh_cli/config.py
  fandogh_cli/domain_commands.py
  fandogh_cli/exceptions.py
  fandogh_cli/fandogh_client/__init__.py
  fandogh_cli/fandogh_client/domain_client.py
  fandogh_cli/image_commands.py
  fandogh_cli/managed_service_commands.py
  fandogh_cli/service_commands.py
  fandogh_cli/utils.py
Labels: enhancement

#107 Enhancement/subdomain verificiation
  fandogh_cli/domain_commands.py
Labels: enhancement

#108 Explain verification of subdomains
  Readme.md
Labels: enhancement

#118 Add api-contract
  api-docs/api-contract.yaml
Labels: enhancement

#129 Add requirements to setup.py
  setup.py
Labels: enhancement

#130 fix py2 compatibility issue
  fandogh_cli/fandogh_client/secrets_client.py
Labels: bug

#134 - Delete image command reflects response message now
  fandogh_cli/fandogh_client/__init__.py
  fandogh_cli/image_commands.py
Labels: enhancement

#136 No-existence-message-for-image-and-service
  fandogh_cli/fandogh.py
  fandogh_cli/image_commands.py
  fandogh_cli/service_commands.py
Labels: enhancement

#137 - Login-instruction
  fandogh_cli/fandogh.py
Labels: enhancement

#135 Enhancement/multiple internal ports
  fandogh_cli/base_commands.py
  fandogh_cli/fandogh_client/__init__.py
  fandogh_cli/service_commands.py
Labels: enhancement

#138 Implement require commands for obtaining certificates
  fandogh_cli/domain_commands.py
  fandogh_cli/fandogh.py
  fandogh_cli/fandogh_client/domain_client.py
  fandogh_cli/fandogh_client/secrets_client.py
Labels: enhancement

#139 Enhancement/#190 certificate request
  fandogh_cli/domain_commands.py
Labels: enhancement

#142 Feature/service realtime log
  fandogh_cli/fandogh_client/__init__.py
  fandogh_cli/service_commands.py
Labels: FandoghAPI, enhancement

#146 service-realtime-log
  fandogh_cli/service_commands.py
Labels: bug

#143 add-service-and-s-for-destroy-service
  fandogh_cli/image_commands.py
  fandogh_cli/service_commands.py
Labels: enhancement

#148 bugfix/image-build-resource-not-found
  fandogh_cli/image_commands.py
Labels: FandoghAPI, bug, enhancement
