Repository fandoghpaas/fandogh-cli, pull requests merged in 2018-07, with the labels that each got.

#69 update: Github url
  setup.py
Labels: bug

#70 Remove "(Email)" from username label
  fandogh_cli/fandogh.py
Labels: bug

#73 Feature/add help for managed service
  fandogh_cli/fandogh_client/__init__.py
  fandogh_cli/managed_service_commands.py
Labels: enhancement

#74 Raise 400Response Exception to display details of error
  fandogh_cli/managed_service_commands.py
Labels: enhancement

#86 Increase version to 0.3.15
  fandogh_cli/__init__.py
Labels: bug, enhancement

#85 Enhancement/display all urls after deploy
  fandogh_cli/fandogh_client/__init__.py
  fandogh_cli/service_commands.py
Labels: bug, enhancement

#95 Explain how to submit and verify new domain name
  Readme.md
Labels: enhancement

#101 Fix the way service destroy process responses
  fandogh_cli/fandogh_client/__init__.py
Labels: bug
