Repository fandoghpaas/fandogh-cli, pull requests merged in 2018-10, with the labels that each got.

#167 - RequestException error collected.
  fandogh_cli/base_commands.py
  fandogh_cli/info_collector.py
Labels: bug, enhancement

#169 - service domains added to details
  fandogh_cli/presenter/service_presenter.py
Labels: enhancement

#173 - Destroy message added.
  fandogh_cli/service_commands.py
Labels: FandoghAPI, enhancement

#174 Feature/multiple services one yaml
  fandogh_cli/service_commands.py
Labels: FandoghAPI, enhancement

#175 - yaml dump bug fixed.
  fandogh_cli/service_commands.py
Labels: bug, enhancement

#176 Display service urls after deploying managed-service
  fandogh_cli/managed_service_commands.py
Labels: bug
