Repository fandoghpaas/fandogh-cli, pull requests merged in 2020-09, with the labels that each got.

#258 Cluster hot fix
  fandogh_cli/cluster_commands.py
Labels: bug

#262 feature/image-publish-retry-policy
  fandogh_cli/fandogh_client/__init__.py
  requirements.txt
Labels: FandoghAPI, enhancement

#261 feature/image-build-timestamp-serializer
  fandogh_cli/fandogh_client/__init__.py
  fandogh_cli/image_commands.py
  fandogh_cli/source_commands.py
Labels: FandoghAPI, enhancement, feature

#263 bugfix/cli-retrying-dependency
  setup.py
Labels: bug

#265 bugfix/show-image-log-timestamp-bug
  fandogh_cli/image_commands.py
Labels: bug
